from my_project.movies.domain.actor import Actor
from my_project.movies.dao.orders.actors_dao import ActorDAO
from my_project.movies.domain.director import Director
from my_project.movies.dao.orders.director_dao import DirectorDAO
from my_project.movies.domain.studio import Studio
from my_project.movies.dao.orders.studio_dao import StudioDAO
from my_project.movies.domain.movie import Movie
from my_project.movies.dao.orders.movie_dao import MovieDAO
from my_project.movies.domain.fact import Fact
from my_project.movies.dao.orders.fact_dao import FactDAO
from ..domain.genre import Genre
from ..dao.orders.genre_dao import GenreDAO
from ..domain.festival import Festival
from ..dao.orders.festival_dao import FestivalDAO
from ..domain.award import Award
from ..dao.orders.award_dao import AwardDAO
from ..domain.review import Review
from ..dao.orders.review_dao import ReviewDAO
from ..domain.rating import Rating
from ..dao.orders.rating_dao import RatingDAO
from ..domain.actors_in_movie import ActorsInMovie
from ..dao.orders.actors_in_movie_dao import ActorsInMovieDAO
from ..domain.movie_genre import MovieGenre
from ..dao.orders.movie_genre_dao import MovieGenreDAO
from ..domain.movie_festival import MovieFestival
from ..dao.orders.movie_festival_dao import MovieFestivalDAO
from ..domain.movie_award import MovieAward
from ..dao.orders.movie_award_dao import MovieAwardDAO
