from my_project.movies.service.orders.actor_service import ActorService
from ..service.orders.director_service import DirectorService
from ..service.orders.studio_service import StudioService
from ..service.orders.movie_service import MovieService
from ..service.orders.fact_service import FactService
from ..service.orders.genre_service import GenreService
from ..service.orders.festival_service import FestivalService
from ..service.orders.award_service import AwardService
from ..service.orders.review_service import ReviewService
from ..service.orders.rating_orders import RatingService
from ..service.orders.actors_in_movie_service import ActorsInMovieService
from ..service.orders.movie_genre_service import MovieGenreService
from ..service.orders.movie_festival_service import MovieFestivalService
from ..service.orders.movie_award_service import MovieAwardService
from ..service.orders.nomination_service import NominationService