from my_project.movies.domain.actor import Actor
from my_project.movies.domain.director import Director
from my_project.movies.domain.studio import Studio
from my_project.movies.domain.movie import Movie
from my_project.movies.domain.fact import Fact
from my_project.movies.domain.genre import Genre
from ..domain.festival import Festival
from ..domain.award import Award
from ..domain.review import Review
from ..domain.rating import Rating
from ..domain.actors_in_movie import ActorsInMovie
from ..domain.movie_genre import MovieGenre
from ..domain.movie_festival import MovieFestival
from ..domain.movie_award import MovieAward
